# mysql-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS products_database;
    USE products_database;
    
    CREATE TABLE IF NOT EXISTS inventory (
                                             id INT PRIMARY KEY AUTO_INCREMENT,
                                             product_name VARCHAR(255) NOT NULL,
                                             quantity INT NOT NULL,
                                             price DECIMAL(10,2) NOT NULL
    );
    
    -- Insert initial inventory data
    INSERT INTO inventory (product_name, quantity, price) VALUES
                                                              ('Product A', 100, 29.99),
                                                              ('Product B', 150, 19.99),
                                                              ('Product C', 75, 39.99);

---
# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: products_database
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init-scripts
          configMap:
            name: mysql-init-scripts

---
# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # 'rootpassword' in base64

---
# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
