---
# Billing Service (Consumer) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service-deployment
spec:
  selector:
    matchLabels:
      app: billing-service-deployment
  template:
    metadata:
      labels:
        app: billing-service-deployment
    spec:
      containers:
        - name: billing-service-container
          image: billing-service-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "billing-group-id"
            - name: KAFKA_AUTO_OFFSET_RESET
              value: "earliest"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
