---
# Inventory Service (Consumer) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
spec:
  selector:
    matchLabels:
      app: inventory-service-deployment
  template:
    metadata:
      labels:
        app: inventory-service-deployment
    spec:
      containers:
        - name: inventory-service-container
          image: inventory-service-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "inventory-group-id"
            - name: KAFKA_AUTO_OFFSET_RESET
              value: "earliest"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
