---
# Billing Service
apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  type: NodePort
  selector:
    app: billing-service-deployment
  ports:
    - port: 8082
      targetPort: 8082
